### ISSUE TITLE
Support use of custom node

### ISSUE THREAD

**Issue by fawaf** [gtramontina/docker-diagrams#53]
because the file is `cat`ed, custom resources cannot be used easily

https://diagrams.mingrammer.com/docs/nodes/custom

**Comment by davidverweij** [comment]
@fawaf you can override the `entrypoint` and mount a directory to pick on a file directly, rather than pipe it in. My setup for a small repo:

```yml
# docker-compose.yml
services:
  diagrams:
    image: gtramontina/diagrams:0.23.3
    restart: 'no'
    volumes:
      - ./:/out
    entrypoint: ['python', '${FILE}']
```
then run:
```sh
FILE=path/to/your/file.py docker-compose up 
```
